# Generated by Django 4.2.3 on 2023-07-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('apto', models.CharField(max_length=255)),
                ('telefone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField(null=True)),
            ],
        ),
    ]
