# Generated by Django 4.2.3 on 2023-07-21 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_morador_descripiton'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='assunto',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
