# Generated by Django 4.2.3 on 2023-07-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sorvete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('A', 'Açaí'), ('C', 'Cupuaçu')], default='A', max_length=1)),
                ('cobertura', models.CharField(choices=[('Cho', 'Chocolate'), ('Mor', 'Morango'), ('car', 'caramelo'), ('leC', 'Leite Condesado')], default='leC', max_length=3)),
                ('tamanho', models.CharField(choices=[('PEQ', 'Pequeno'), ('MED', 'Médio'), ('GRD', 'Grande'), ('BRC', 'Barca')], default='MED', max_length=3)),
            ],
        ),
    ]
